version: '3'

networks:
  ged:

services:
  
  server:
    container_name: server
    user: 1000:1000
    build:
      context: .
      dockerfile: './.docker/server/Dockerfile.dev'
    ports:
      - 3000:3000
    volumes:
      - './api/:/home/node/api'
    networks:
      - ged

  mongo:
    container_name: db
    image: mongo:jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./.docker/database/mongo_data:/data/db"
    networks:
      - ged

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - ged